# DEJA LOG EN ESCRITORIO CON TEMPERATURA POR SEGUNDO AL MOVER SISTEMA, ABRIR TODO, CERRAR ETC...
while true; do echo "$(date '+%Y-%m-%d %H:%M:%S') --- $(sensors | grep 'Core')" >> ~/Desktop/log_temperatura.txt; sleep 1; done
